import { Button } from "@/components/ui/button";
import { OrbiqoMark } from "@/components/OrbiqoMark";
import { ReaderWorkspace } from "@/components/ReaderWorkspace";
import { BenchmarkWorkspace } from "@/components/BenchmarkWorkspace";
import { ComparisonWorkspace } from "@/components/ComparisonWorkspace";
import { VisualIdentityPicker } from "@/components/VisualIdentityPicker";
import { ManualGeometrySelect, resolveManualGeometryDefaults } from "@/components/ManualGeometrySelect";
import { CenterImageField } from "@/components/CenterImageField";
import { trpc } from "@/lib/trpc";
import { describeCenterImageError } from "@/lib/centerImageError";
import { brandCopy } from "@/lib/brandCopy";
import { workspaceContext } from "@/lib/workspaceContext";
import type { OrbiqoEcc, OrbiqoGeometry, OrbiqoIdentityId, OrbiqoPayloadType, OrbiqoSizingMode } from "@shared/orbiqo";
import {
  Activity,
  ArrowUpRight,
  Badge,
  Binary,
  Check,
  ChevronDown,
  CircleDotDashed,
  CircleGauge,
  Code2,
  Download,
  FileUp,
  FlaskConical,
  Image as ImageIcon,
  Link2,
  LoaderCircle,
  MapPin,
  ScanLine,
  ShieldCheck,
  Sparkles,
  Type,
  UserRound,
} from "lucide-react";
import { useDeferredValue, useEffect, useRef, useState } from "react";
import { toast } from "sonner";

const samplePayload = "https://orbiqo.dev/lab";

function arrayBufferToBase64(buffer: ArrayBuffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  const chunk = 0x8000;
  for (let index = 0; index < bytes.length; index += chunk) {
    binary += String.fromCharCode(...Array.from(bytes.subarray(index, index + chunk)));
  }
  return btoa(binary);
}

function downloadBlob(contents: BlobPart, type: string, filename: string) {
  const url = URL.createObjectURL(new Blob([contents], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function FieldLabel({ children, hint }: { children: React.ReactNode; hint?: string }) {
  return (
    <label className="field-label">
      <span>{children}</span>
      {hint ? <small>{hint}</small> : null}
    </label>
  );
}

export default function Home() {
  const initialParams = new URLSearchParams(window.location.search);
  const initialSmallReview = initialParams.get("sizing") === "manual" && initialParams.get("geometry") === "small";
  const [payloadType, setPayloadType] = useState<OrbiqoPayloadType>("url");
  const [text, setText] = useState(samplePayload);
  const [binaryBase64, setBinaryBase64] = useState("");
  const [binaryName, setBinaryName] = useState("");
  const [geometry, setGeometry] = useState<OrbiqoGeometry>("small");
  const [diameterMm, setDiameterMm] = useState(30);
  const [sizingMode, setSizingMode] = useState<OrbiqoSizingMode>(initialSmallReview ? "manual" : "auto");
  const [ecc, setEcc] = useState<OrbiqoEcc>("balanced");
  const [centerMark, setCenterMark] = useState("OQ");
  const [centerImageUrl, setCenterImageUrl] = useState(() => initialParams.get("centerImageUrl") ?? "");
  const [centerImageDismissed, setCenterImageDismissed] = useState(false);
  const [identityId, setIdentityId] = useState<OrbiqoIdentityId>("pulse");
  const [activeView, setActiveView] = useState<"create" | "read" | "compare" | "benchmarks">(() => {
    const requested = new URLSearchParams(window.location.search).get("view");
    return requested === "read" || requested === "compare" || requested === "benchmarks" ? requested : "create";
  });
  const autoGenerated = useRef(false);
  const health = trpc.orbiqo.health.useQuery(undefined, { retry: 1, staleTime: 60_000 });
  const capacities = trpc.orbiqo.capacities.useQuery({ alphabet: "color4", ecc });
  const identities = trpc.orbiqo.identities.useQuery(undefined, { retry: 1, staleTime: Infinity });
  const deferredText = useDeferredValue(text);
  const deferredBinaryBase64 = useDeferredValue(binaryBase64);
  const recommendationEnabled = sizingMode === "auto" && (payloadType !== "binary" || Boolean(deferredBinaryBase64));
  const sizingRecommendation = trpc.orbiqo.recommendSizing.useQuery(
    {
      payloadType,
      text: payloadType === "binary" ? undefined : deferredText,
      payloadBase64: payloadType === "binary" ? deferredBinaryBase64 : undefined,
      alphabet: "color4",
      ecc,
      compression: "auto",
    },
    { enabled: recommendationEnabled, retry: false, staleTime: 5_000 },
  );
  const generate = trpc.orbiqo.generate.useMutation({
    onError(error) {
      toast.error("Generation failed", { description: error.message });
    },
  });

  const request = {
    payloadType,
    text: payloadType === "binary" ? undefined : text,
    payloadBase64: payloadType === "binary" ? binaryBase64 : undefined,
    sizingMode,
    geometry: sizingMode === "auto" ? "auto" as const : geometry,
    diameterMm: sizingMode === "manual" ? diameterMm : undefined,
    alphabet: "color4" as const,
    ecc,
    compression: "auto" as const,
    dpi: 600,
    centerMark: centerMark || undefined,
    centerImageUrl: centerImageUrl.trim() || undefined,
    identityId,
  };

  useEffect(() => {
    if (autoGenerated.current) return;
    autoGenerated.current = true;
    generate.mutate(request);
    // The initial example is intentionally generated once by the real backend.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const selectedCapacity = capacities.data?.rows.find(row =>
    sizingMode === "auto"
      ? row.version === sizingRecommendation.data?.geometry_version
      : typeof geometry === "string" && String(row.name).toLowerCase() === geometry,
  );
  const selectedIdentity = identities.data?.identities.find(identity => identity.id === identityId);
  const activeContext = activeView === "create" ? null : workspaceContext[activeView];
  const centerImageBridgeError = generate.isError && centerImageUrl.trim() && /center image/i.test(generate.error.message)
    ? describeCenterImageError(generate.error.message)
    : null;

  async function handleBinaryFile(file?: File) {
    if (!file) return;
    if (file.size > 64 * 1024) {
      toast.error("Binary payload is too large", { description: "The local bridge limit is 64 KiB." });
      return;
    }
    setBinaryName(file.name);
    setBinaryBase64(arrayBufferToBase64(await file.arrayBuffer()));
  }

  function handleGenerate() {
    if (payloadType === "binary" && !binaryBase64) {
      toast.error("Choose a binary file first");
      return;
    }
    if (centerImageUrl.trim() && !/^https:\/\//i.test(centerImageUrl.trim())) {
      toast.error("Center image URL must use HTTPS");
      return;
    }
    setCenterImageDismissed(false);
    generate.mutate(request);
  }

  function downloadSvg() {
    if (!generate.data) return;
    downloadBlob(generate.data.svg, "image/svg+xml;charset=utf-8", "orbiqo.svg");
  }

  function downloadPng() {
    if (!generate.data) return;
    const bytes = Uint8Array.from(atob(generate.data.png_base64), char => char.charCodeAt(0));
    downloadBlob(bytes, "image/png", "orbiqo.png");
  }

  return (
    <div className="lab-shell">
      <header className="lab-header">
        <a className="brand-lockup" href="#top" aria-label="Orbiqo Lab home">
          <OrbiqoMark />
          <span>
            <strong>Orbiqo</strong>
            <small>LAB / PROTOCOL DRAFT 0.6</small>
          </span>
        </a>
        <nav className="view-switcher" aria-label="Workspace views">
          {(["create", "read", "compare", "benchmarks"] as const).map(view => (
            <button
              className={activeView === view ? "is-active" : ""}
              key={view}
              onClick={() => {
                setActiveView(view);
                const url = new URL(window.location.href);
                if (view === "create") url.searchParams.delete("view");
                else url.searchParams.set("view", view);
                window.history.replaceState({}, "", url);
              }}
              type="button"
            >
              {view === "create" ? "Create" : view === "read" ? "Read" : view === "compare" ? "Compare" : "Benchmarks"}
            </button>
          ))}
        </nav>
        <div className="runtime-status" title={health.data?.reference_root}>
          <span className={health.isSuccess ? "status-dot is-online" : "status-dot"} />
          <span>{health.isSuccess ? `${brandCopy.runtimePrefix} ${health.data.reference_version}` : "Checking Orbiqo reference"}</span>
        </div>
      </header>

      <main id="top" className="lab-main">
        {activeContext ? (
          <section className="workspace-context" aria-labelledby="workspace-context-title">
            <div>
              <p className="eyebrow"><Sparkles size={14} /> {activeContext.eyebrow}</p>
              <h1 id="workspace-context-title">{activeContext.lead} <em>{activeContext.emphasis}</em></h1>
            </div>
            <p>{activeContext.body}</p>
          </section>
        ) : (
          <>
            <section className="intro-band">
              <div>
                <p className="eyebrow"><Sparkles size={14} /> {brandCopy.adoptionPitch.eyebrow}</p>
                <h1>{brandCopy.heroLead}<br /><em>{brandCopy.heroEmphasis}</em></h1>
              </div>
              <div className="intro-copy">
                <p>{brandCopy.productDescription}</p>
                <span><ShieldCheck size={16} /> Real encoder · no mock path</span>
              </div>
            </section>

            <section className="adoption-strip" aria-label="Reasons to choose Orbiqo">
              {brandCopy.adoptionPitch.reasons.map((reason, index) => (
                <article key={reason.label}>
                  <span>0{index + 1}</span>
                  <div>
                    <small>{reason.label}</small>
                    <h2>{reason.title}</h2>
                    <p>{reason.body}</p>
                  </div>
                </article>
              ))}
            </section>
          </>
        )}

        {activeView === "create" ? (
          <section className="workspace-grid">
            <div className="control-panel">
              <div className="panel-heading">
                <span className="step-index">01</span>
                <div><p>Payload</p><h2>What should it carry?</h2></div>
              </div>

              <div className="payload-tabs" role="tablist" aria-label="Payload type">
                {([
                  ["url", Link2, "URL"],
                  ["text", Type, "Text"],
                  ["binary", Binary, "Binary"],
                ] as const).map(([value, Icon, label]) => (
                  <button key={value} className={payloadType === value ? "is-active" : ""} onClick={() => setPayloadType(value)} type="button">
                    <Icon size={15} /> {label}
                  </button>
                ))}
              </div>

              {payloadType === "binary" ? (
                <label className="binary-drop">
                  <FileUp size={22} />
                  <span>{binaryName || "Choose a binary file"}</span>
                  <small>Maximum 64 KiB before framing</small>
                  <input type="file" onChange={event => void handleBinaryFile(event.target.files?.[0])} />
                </label>
              ) : (
                <div className="field-stack">
                  <FieldLabel hint={`${new TextEncoder().encode(text).length} bytes`}>{payloadType === "url" ? "Destination URL" : "Message"}</FieldLabel>
                  <textarea
                    className="lab-textarea"
                    rows={payloadType === "url" ? 2 : 5}
                    value={text}
                    onChange={event => setText(event.target.value)}
                    placeholder={payloadType === "url" ? "https://example.com" : "Enter UTF-8 text"}
                  />
                </div>
              )}

              <div className="section-rule" />
              <div className="panel-heading panel-heading--compact">
                <span className="step-index">02</span>
                <div><p>Symbol</p><h2>Fit the payload</h2></div>
              </div>

              <div className="sizing-mode-switch" role="tablist" aria-label="Symbol sizing mode">
                <button className={sizingMode === "auto" ? "is-active" : ""} onClick={() => setSizingMode("auto")} role="tab" aria-selected={sizingMode === "auto"} type="button">
                  <Sparkles size={14} /><span><strong>Auto fit</strong><small>Smallest compatible symbol</small></span>
                </button>
                <button className={sizingMode === "manual" ? "is-active" : ""} onClick={() => setSizingMode("manual")} role="tab" aria-selected={sizingMode === "manual"} type="button">
                  <CircleGauge size={14} /><span><strong>Manual</strong><small>Override geometry and diameter</small></span>
                </button>
              </div>

              {sizingMode === "auto" ? (
                <div className={`auto-sizing-card ${sizingRecommendation.isError ? "is-error" : ""}`}>
                  {sizingRecommendation.isFetching ? (
                    <div className="auto-sizing-loading"><LoaderCircle className="animate-spin" size={16} /> Calculating encoded frame…</div>
                  ) : sizingRecommendation.data ? (
                    <>
                      <div className="auto-sizing-result">
                        <span>Recommended output</span>
                        <strong>{sizingRecommendation.data.geometry_name} · {sizingRecommendation.data.recommended_diameter_mm} mm</strong>
                      </div>
                      <div className="auto-sizing-metrics">
                        <span>{sizingRecommendation.data.payload_bytes} B payload</span>
                        <span>{sizingRecommendation.data.frame_bytes} B frame</span>
                        <span>{sizingRecommendation.data.compression}</span>
                        <span>{sizingRecommendation.data.remaining_nominal_payload_bytes} B spare</span>
                      </div>
                      <p>Smallest geometry that fits the encoded frame with {ecc} protection.</p>
                    </>
                  ) : sizingRecommendation.isError ? (
                    <><strong>Payload exceeds the available geometries</strong><p>{sizingRecommendation.error.message}</p></>
                  ) : (
                    <p>Choose a binary file to calculate its symbol size.</p>
                  )}
                </div>
              ) : (
                <div className="form-grid form-grid--manual-sizing">
                  <ManualGeometrySelect value={geometry} onChange={nextGeometry => {
                      const defaults = resolveManualGeometryDefaults(nextGeometry);
                      setGeometry(defaults.geometry);
                      if (defaults.ecc) setEcc(defaults.ecc);
                      if (defaults.diameterMm) setDiameterMm(defaults.diameterMm);
                    }} />
                  <div className="field-stack">
                    <FieldLabel hint="10–300 mm">Diameter</FieldLabel>
                    <div className="unit-input"><input type="number" min={10} max={300} step={1} value={diameterMm} onChange={event => setDiameterMm(Number(event.target.value))} /><span>mm</span></div>
                  </div>
                </div>
              )}

              <div className="form-grid form-grid--secondary">
                <div className="field-stack">
                  <FieldLabel hint="Capacity vs recovery">Protection profile</FieldLabel>
                  <div className="select-wrap"><select value={ecc} onChange={event => setEcc(event.target.value as OrbiqoEcc)}>
                    <option value="fast">Fast</option><option value="balanced" disabled={sizingMode === "manual" && geometry === "micro-1"}>Balanced</option><option value="robust" disabled={sizingMode === "manual" && geometry === "micro-1"}>Robust</option><option value="extreme" disabled={sizingMode === "manual" && geometry === "micro-1"}>Extreme</option>
                  </select><ChevronDown size={15} /></div>
                </div>
                <div className="field-stack">
                  <FieldLabel hint="Non-functional">Center mark</FieldLabel>
                  <input className="lab-input" maxLength={8} value={centerMark} onChange={event => setCenterMark(event.target.value)} placeholder="OQ" />
                </div>
              </div>

              <CenterImageField
                value={centerImageUrl}
                onChange={value => {
                  setCenterImageUrl(value);
                  if (value.trim()) setCenterImageDismissed(false);
                }}
                onClear={() => {
                  setCenterImageUrl("");
                  setCenterImageDismissed(true);
                }}
                previewBase64={centerImageDismissed ? undefined : generate.data?.center_image_preview_base64}
                host={centerImageDismissed ? undefined : generate.data?.metadata.center_image_host}
                error={centerImageBridgeError}
              />

              <div className="visual-identity-field">
                <FieldLabel hint="Validated visual templates">Visual identity</FieldLabel>
                <p className="identity-explainer">Each template combines a validated palette with a safe cell profile. Free-form colors remain disabled.</p>
                <VisualIdentityPicker identities={identities.data?.identities} loading={identities.isLoading} selectedId={identityId} onSelect={setIdentityId} />
              </div>

              <div className="capacity-line">
                <CircleGauge size={17} />
                <span>{sizingMode === "auto" ? "Selected capacity" : "Nominal capacity"}</span>
                <strong>{selectedCapacity?.maximum_uncompressed_payload_bytes ?? "—"} bytes</strong>
              </div>

              <Button className="generate-button" onClick={handleGenerate} disabled={generate.isPending || (sizingMode === "auto" && sizingRecommendation.isError)}>
                {generate.isPending ? <LoaderCircle className="animate-spin" size={18} /> : <Sparkles size={18} />}
                {generate.isPending ? "Encoding through C++…" : "Generate Orbiqo"}
                {!generate.isPending ? <ArrowUpRight size={18} /> : null}
              </Button>
            </div>

            <div className="preview-panel">
              <div className="preview-toolbar">
                <div><span className="step-index step-index--dark">03</span><div><p>Artifact / visual identity</p><h2>{generate.data?.metadata.identity_name ?? selectedIdentity?.name ?? "Pulse"}</h2></div></div>
                <span className="real-badge"><Check size={13} /> {generate.data?.metadata.palette_name ?? selectedIdentity?.palette_name ?? "Validated palette"}</span>
              </div>

              <div className="symbol-stage">
                <div className="stage-orbit stage-orbit--one" /><div className="stage-orbit stage-orbit--two" />
                {generate.data ? (
                  <img src={`data:image/png;base64,${generate.data.png_base64}`} alt="Generated Orbiqo symbol" />
                ) : (
                  <div className="symbol-loading"><LoaderCircle className="animate-spin" /><span>Calling reference encoder</span></div>
                )}
              </div>

              <div className="export-row">
                <button onClick={downloadSvg} disabled={!generate.data} type="button"><Code2 size={16} /><span><strong>SVG</strong><small>Vector + metadata</small></span><Download size={16} /></button>
                <button onClick={downloadPng} disabled={!generate.data} type="button"><ImageIcon size={16} /><span><strong>PNG</strong><small>600 DPI raster</small></span><Download size={16} /></button>
              </div>

              <div className="diagnostic-strip">
                <div><span>Geometry</span><strong>{generate.data?.metadata.geometry_name ?? "—"}</strong></div>
                <div><span>Diameter</span><strong>{generate.data ? `${generate.data.metadata.diameter_mm} mm` : "—"}</strong></div>
                <div><span>Sizing</span><strong>{generate.data?.metadata.sizing_mode ?? "—"}</strong></div>
                <div><span>Identity</span><strong>{generate.data?.metadata.identity_name ?? "—"}</strong></div>
              </div>
              <p className="attribution-line">{brandCopy.artifactAttribution}</p>
            </div>
          </section>
        ) : activeView === "read" ? (
          <ReaderWorkspace
            samplePngBase64={generate.data?.png_base64}
            sampleGeometryVersion={generate.data?.metadata.geometry_version}
          />
        ) : activeView === "compare" ? (
          <ComparisonWorkspace
            payloadType={payloadType}
            text={payloadType === "binary" ? undefined : text}
            payloadBase64={payloadType === "binary" ? binaryBase64 : undefined}
            identityId={identityId}
            centerMark={centerMark || undefined}
          />
        ) : <BenchmarkWorkspace />}

        <section className="circular-fit-section" aria-labelledby="circular-fit-title">
          <header className="circular-fit-heading">
            <div>
              <p className="eyebrow"><CircleDotDashed size={14} /> {brandCopy.circularPositioning.eyebrow}</p>
              <h2 id="circular-fit-title">{brandCopy.circularPositioning.headlineLead} <em>{brandCopy.circularPositioning.headlineEmphasis}</em></h2>
            </div>
            <p>{brandCopy.circularPositioning.description}</p>
          </header>

          <div className="circular-fit-grid">
            <article className="circular-footprint-card">
              <div className="circular-geometry-figure" aria-hidden="true"><i /><b /></div>
              <div className="circular-footprint-copy">
                <span>ROUND-OBJECT GEOMETRY</span>
                <strong>63.7%</strong>
                <p>{brandCopy.circularPositioning.footprint}</p>
                <small>{brandCopy.circularPositioning.footprintLimit}</small>
              </div>
            </article>

            <div className="circular-use-grid">
              <article className="circular-use-card circular-use-card--profile">
                <UserRound /><div><span>PROFILE / PEOPLE</span><h3>Recognition with a human center</h3><p>A photo or mark can live in the non-functional center while the encoded rings remain around it—friendlier for directories, event passes and personal identities.</p></div>
              </article>
              <article className="circular-use-card">
                <Badge /><div><span>BADGES / BROOCHES</span><h3>Made for a round pin</h3><p>Lapel pins, club tokens, accreditation badges and collectible medallions no longer need a square label imposed on a circular object.</p></div>
              </article>
              <article className="circular-use-card">
                <CircleGauge /><div><span>PRODUCT SURFACES</span><h3>Use the face already available</h3><p>Caps, coasters, jar lids, wrist tokens and round product seals offer a natural circular face for a code that reads as part of the object.</p></div>
              </article>
              <article className="circular-use-card">
                <MapPin /><div><span>PLACES / MEMBERSHIP</span><h3>A recognizable touchpoint</h3><p>Table markers, loyalty discs and wayfinding tokens can combine a registered visual identity with a scannable action in a familiar circular form.</p></div>
              </article>
            </div>
          </div>

          <aside className="circular-fit-note"><ShieldCheck size={18} /><p><strong>What this does not claim.</strong> {brandCopy.circularPositioning.benchmarkLimit}</p></aside>
        </section>

      </main>

      <footer className="lab-footer">
        <span>ORBIQO LAB / LOCAL BENCHMARK GATE</span>
        <span>{brandCopy.footerProtocol}</span>
      </footer>
    </div>
  );
}
